---
- name: Ansible Facts
  hosts: junex01
  gather_facts: yes

  tasks:

  - name: print facts to console
    debug:
      msg: "{{ansible_facts}}"

  - name: display version
    debug:
      msg: "The version is: {{ ansible_net_version }}"

  - name: display serial number
    debug:
      msg: "The serial number is:{{ ansible_net_serialnum }}"