---
- name: Ansible Facts
  hosts: juniper
  connection: local
  gather_facts: no

  tasks:

  - name: collect default set of facts
    junipernetworks.junos.junos_facts:
    register: j_facts

  - name: print facts to console
    debug:
      msg: "{{ j_facts }}"

  # - name: display version
  #   debug:
  #     msg: "The version is: {{ ansible_net_version }}"

  # - name: display serial number
  #   debug:
  #     msg: "The serial number is:{{ ansible_net_serialnum }}"