---
- name: CONFIGURE INTERFACES
  hosts: juniper
  gather_facts: no

  tasks:
  - name: GATHER CURRENT INTERFACES CONFIGURED
    junipernetworks.junos.junos_interfaces:
      state: gathered

#  - name: CONFIGURE THE PHYSICAL INTERFACES **PREFERRED METHOD USING HOST_VARS**
#    junipernetworks.junos.junos_interfaces:
#      config: "{{ interfaces }}"
#      state: replaced

  # - name: CONFIGURE THE PHYSICAL INTERFACES **EXAMPLE FROM DOCS**
  #   junipernetworks.junos.junos_interfaces:
  #     config:
  #     - name: ge-0/0/1
  #       description: Configured by Ansible
  #       enabled: true
  #       mtu: 1800
  #     - name: ge-0/0/2
  #       description: Configured by Ansible
  #       enabled: false
  #     state: replaced%